"""Detect and strip C2PA / AI-related metadata from PNG, JPEG, WebP, TIFF and GIF (stdlib)."""

from __future__ import annotations

import json
import os
import re
import struct
import subprocess
import sys
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from common import classify_finding_confidence, safe_arg, safe_write_bytes, subprocess_preexec_fn, which

SCRIPTS_DIR = Path(__file__).resolve().parent

# CtrlRegen is torch-based and needs far more address space than the stdlib
# parsers. The invoking clean_image.py subprocess applies these higher,
# env-overridable caps instead of the default child limits in common.py.
_CTRLREGEN_RLIMIT_AS = int(os.environ.get("WATERMARKS_CTRLREGEN_RLIMIT_AS", str(32 << 30)))
_CTRLREGEN_RLIMIT_FSIZE = int(os.environ.get("WATERMARKS_CTRLREGEN_RLIMIT_FSIZE", str(2 << 30)))


def ctrlregen_preexec_fn() -> None:
    """Higher resource caps for the CtrlRegen subprocess (torch memory)."""
    try:
        import resource

        resource.setrlimit(resource.RLIMIT_AS, (_CTRLREGEN_RLIMIT_AS, _CTRLREGEN_RLIMIT_AS))
        resource.setrlimit(resource.RLIMIT_FSIZE, (_CTRLREGEN_RLIMIT_FSIZE, _CTRLREGEN_RLIMIT_FSIZE))
    except (ImportError, OSError, ValueError):
        pass


ctrlregen_subprocess_preexec_fn = ctrlregen_preexec_fn if os.name == "posix" else None

PNG_SIG = b"\x89PNG\r\n\x1a\n"
JPEG_SOI = b"\xff\xd8"
WEBP_RIFF = b"RIFF"
WEBP_MAGIC = b"WEBP"
TIFF_LE = b"II*\x00"
TIFF_BE = b"MM\x00*"
GIF_SIGS = (b"GIF87a", b"GIF89a")

# Chunk types / content patterns associated with C2PA / AI provenance
C2PA_MARKERS = (
    b"c2pa",
    b"C2PA",
    b"jumb",
    b"JUMB",
    b"c2ma",
    b"contentcredentials",
    b"contentauth",
    b"cai:",
    b"http://ns.adobe.com/xmp/InstanceID/",  # not solely C2PA
)

AI_META_HINTS = (
    b"c2pa",
    b"C2PA",
    b"contentcredentials",
    b"ContentCredentials",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"aigc",
    b"AI generated",
    b"Generated by",
    b"Claude",
    b"Anthropic",
    b"OpenAI",
    b"SynthID",
    b"dcterms:provenance",
)


@dataclass
class ImageInspectReport:
    path: str
    format: str  # png | jpeg | unknown
    has_c2pa: bool
    has_ai_metadata: bool
    findings: list[str] = field(default_factory=list)
    tools: dict[str, Any] = field(default_factory=dict)
    synthid: dict[str, Any] | None = None
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "format": self.format,
            "has_c2pa": self.has_c2pa,
            "has_ai_metadata": self.has_ai_metadata,
            "findings": self.findings,
            "findings_confidence": [
                classify_finding_confidence(f) for f in self.findings
            ],
            "tools": self.tools,
            "synthid": self.synthid,
            "notes": self.notes,
        }


def detect_format(data: bytes) -> str:
    if data.startswith(PNG_SIG):
        return "png"
    if data.startswith(JPEG_SOI):
        return "jpeg"
    if data[:4] == WEBP_RIFF and data[8:12] == WEBP_MAGIC:
        return "webp"
    if data[:4] in (TIFF_LE, TIFF_BE):
        return "tiff"
    if data[:6] in GIF_SIGS:
        return "gif"
    return "unknown"


def _contains_any(blob: bytes, needles: tuple[bytes, ...]) -> list[str]:
    found = []
    lower = blob.lower()
    for n in needles:
        if n.lower() in lower:
            try:
                found.append(n.decode("ascii", errors="replace"))
            except Exception:
                found.append(repr(n))
    return found


def inspect_png(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if not data.startswith(PNG_SIG):
        return False, False, ["not a PNG"]
    pos = 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        ctype = data[pos + 4 : pos + 8]
        chunk_start = pos + 8
        chunk_end = chunk_start + length
        if chunk_end + 4 > len(data):
            findings.append(f"truncated chunk {ctype!r}")
            break
        payload = data[chunk_start:chunk_end]
        name = ctype.decode("latin-1", errors="replace")
        # Private/ancillary chunks sometimes used for JUMBF/C2PA
        if ctype in (b"caBX", b"juMB", b"jumb") or ctype.startswith(b"c2"):
            has_c2pa = True
            findings.append(f"PNG chunk {name} (possible C2PA container)")
        if ctype in (b"tEXt", b"zTXt", b"iTXt", b"eXIf"):
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(h.lower() in ("c2pa", "contentcredentials", "jumb") for h in hits):
                    has_c2pa = True
                findings.append(f"PNG {name}: {', '.join(hits[:8])}")
        if ctype == b"IEND":
            break
        pos = chunk_end + 4  # skip CRC
    # Whole-file scan fallback
    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


def inspect_jpeg(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if not data.startswith(JPEG_SOI):
        return False, False, ["not a JPEG"]
    i = 2
    n = len(data)
    while i + 4 <= n:
        if data[i] != 0xFF:
            i += 1
            continue
        # skip fill
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1
        if marker in (0xD8, 0xD9):  # SOI/EOI
            continue
        if marker == 0xDA:  # SOS — image data follows
            break
        if marker >= 0xD0 and marker <= 0xD7:  # RSTn
            continue
        if i + 2 > n:
            break
        seglen = struct.unpack(">H", data[i : i + 2])[0]
        if seglen < 2 or i + seglen > n:
            findings.append(f"bad segment length at marker 0x{marker:02X}")
            break
        payload = data[i + 2 : i + seglen]
        i += seglen

        # APP11 (0xEB) often holds JUMBF/C2PA
        if marker == 0xEB:
            has_c2pa = True
            findings.append("JPEG APP11 segment (JUMBF/C2PA common)")
        if marker in (0xE1, 0xE2, 0xED, 0xEE, 0xEB):  # APP1,2,13,14,11
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(
                    h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth")
                    for h in hits
                ):
                    has_c2pa = True
                findings.append(f"JPEG APP{marker - 0xE0}: {', '.join(hits[:8])}")

    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


# --- WebP ---------------------------------------------------------------------

def _webp_chunks(data: bytes):
    """Yield (fourcc, payload, truncated) over chunks after the 12-byte header."""
    pos = 12
    n = len(data)
    while pos + 8 <= n:
        fourcc = data[pos : pos + 4]
        size = struct.unpack("<I", data[pos + 4 : pos + 8])[0]
        payload = data[pos + 8 : pos + 8 + size]
        yield fourcc, payload, len(payload) < size
        if len(payload) < size:
            break
        pos += 8 + size + (size & 1)  # chunks are padded to even length


def inspect_webp(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if data[:4] != WEBP_RIFF or data[8:12] != WEBP_MAGIC:
        return False, False, ["not a WebP"]
    for fourcc, payload, truncated in _webp_chunks(data):
        name = fourcc.decode("latin-1", errors="replace")
        if truncated:
            findings.append(f"truncated WebP chunk {name!r}")
            break
        if fourcc in (b"EXIF", b"XMP "):
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(h.lower() in ("c2pa", "contentcredentials", "jumb") for h in hits):
                    has_c2pa = True
                findings.append(f"WebP {name}: {', '.join(hits[:8])}")
            else:
                findings.append(f"info: WebP {name} chunk present")
    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


# --- TIFF ---------------------------------------------------------------------

# Tags that carry provenance rather than pixels. EXIF/XMP pointers are noted
# separately (they lead to whole metadata trees).
_TIFF_TEXT_TAGS = {
    270: "ImageDescription",
    305: "Software",
    306: "DateTime",
    315: "Artist",
    316: "HostComputer",
    33432: "Copyright",
    40091: "XPTitle",
    40092: "XPComment",
    40093: "XPAuthor",
    40094: "XPKeywords",
    40095: "XPSubject",
}
_TIFF_TYPE_SIZE = {1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 6: 1, 7: 1, 8: 2, 9: 4, 10: 8, 11: 4, 12: 8}
_TIFF_TAG_VALUE_READ_LIMIT = 4096  # per-tag byte cap while sniffing hints


def _tiff_ifd_entries(data: bytes, offset: int, le: bool):
    """Yield (tag, type, count, value_offset, entry_offset) for one IFD."""
    fmt = "<" if le else ">"
    n = len(data)
    if offset + 2 > n:
        return
    (count,) = struct.unpack_from(fmt + "H", data, offset)
    count = min(count, 512)  # defensive cap
    for i in range(count):
        entry = offset + 2 + i * 12
        if entry + 12 > n:
            break
        tag, typ, cnt = struct.unpack_from(fmt + "HHI", data, entry)
        (val_off,) = struct.unpack_from(fmt + "I", data, entry + 8)
        yield tag, typ, cnt, val_off, entry


def _tiff_walk_ifds(data: bytes, le: bool, ifd0_offset: int):
    """Yield (tag, type, count, value_offset, entry_offset) across the IFD chain."""
    fmt = "<" if le else ">"
    n = len(data)
    seen: set[int] = set()
    offset = ifd0_offset
    for _ in range(16):  # chained IFDs, bounded defensively
        if offset in seen or offset + 2 > n:
            break
        seen.add(offset)
        (count,) = struct.unpack_from(fmt + "H", data, offset)
        count = min(count, 512)
        entries_end = offset + 2 + count * 12
        if entries_end + 4 > n:
            # next-IFD pointer must sit right after the last entry
            yield from _tiff_ifd_entries(data, offset, le)
            break
        yield from _tiff_ifd_entries(data, offset, le)
        (next_off,) = struct.unpack_from(fmt + "I", data, entries_end)
        offset = next_off


def _tiff_value_bytes(
    data: bytes, le: bool, typ: int, cnt: int, val_off: int, entry: int
) -> bytes:
    """Read a tag value: inline (<=4 bytes, lives in the entry) or at *val_off*."""
    size = _TIFF_TYPE_SIZE.get(typ, 1) * cnt
    if size <= 4:
        return data[entry + 8 : entry + 8 + size]
    size = min(size, _TIFF_TAG_VALUE_READ_LIMIT)
    if val_off + size > len(data):
        return b""
    return data[val_off : val_off + size]


def inspect_tiff(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    le = data[:4] == TIFF_LE
    if not le and data[:4] != TIFF_BE:
        return False, False, ["not a TIFF"]
    (ifd0,) = struct.unpack_from("<I" if le else ">I", data, 4)

    blob = bytearray()
    for tag, typ, cnt, val_off, entry in _tiff_walk_ifds(data, le, ifd0):
        if tag in _TIFF_TEXT_TAGS:
            blob += _tiff_value_bytes(data, le, typ, cnt, val_off, entry)
        elif tag in (34665, 34853):  # EXIF / GPS IFD pointers
            findings.append(
                f"info: TIFF {'EXIF' if tag == 34665 else 'GPS'} IFD present "
                "(metadata tree; strip zeroes the pointer)"
            )
    hits = _contains_any(bytes(blob), AI_META_HINTS + C2PA_MARKERS)
    if hits:
        has_ai = True
        if any(h.lower() in ("c2pa", "contentcredentials", "jumb") for h in hits):
            has_c2pa = True
        findings.append(f"TIFF metadata tags: {', '.join(hits[:8])}")
    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


# --- GIF ----------------------------------------------------------------------

def _gif_walk_blocks(data: bytes):
    """Yield (block_bytes, kind, label) for top-level GIF blocks after the LSD.

    kind is "extension" (label = extension label), "image", or "trailer".
    Image data is opaque (LZW sub-blocks) and copied verbatim.
    """
    pos = 13  # header (6) + logical screen descriptor (7)
    n = len(data)
    while pos < n:
        b = data[pos]
        if b == 0x3B:  # trailer
            yield data[pos : pos + 1], "trailer", None
            return
        if b == 0x21:  # extension
            if pos + 2 > n:
                return
            label = data[pos + 1]
            p = pos + 2
            if label == 0xF9 and p < n:  # graphic control: fixed 4-byte block
                block_size = data[p]
                p += 1 + block_size + 1  # size + payload + terminator
                end = min(p, n)
                yield data[pos:end], "extension", label
                pos = end
                continue
            if label == 0xFF:  # application extension: size byte + 11-byte id first
                p += 1 + 11
            while p < n and data[p] != 0:  # sub-block chain
                p += 1 + data[p]
            p += 1  # terminator
            end = min(p, n)
            yield data[pos:end], "extension", label
            pos = end
            continue
        if b == 0x2C:  # image descriptor
            p = pos + 10  # separator + descriptor (9 bytes)
            if p > n:
                return
            packed = data[pos + 9]
            if packed & 0x80:  # local color table
                table_bits = (packed & 0x07) + 1
                p += 3 * (1 << table_bits)
            if p < n:
                p += 1  # LZW minimum code size
                while p < n and data[p] != 0:
                    p += 1 + data[p]
                p += 1
            end = min(p, n)
            yield data[pos:end], "image", None
            pos = end
            continue
        # Unknown byte: no safe recovery point — copy the rest verbatim.
        yield data[pos:], "unknown", None
        return


def inspect_gif(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if data[:6] not in GIF_SIGS:
        return False, False, ["not a GIF"]
    for block, kind, label in _gif_walk_blocks(data):
        if kind != "extension" or label not in (0xFE, 0xFF):
            continue
        name = "comment extension" if label == 0xFE else "application extension"
        hits = _contains_any(block, AI_META_HINTS + C2PA_MARKERS)
        if hits:
            has_ai = True
            if any(h.lower() in ("c2pa", "contentcredentials", "jumb") for h in hits):
                has_c2pa = True
            findings.append(f"GIF {name}: {', '.join(hits[:8])}")
        elif label == 0xFE:
            findings.append(f"info: GIF {name} present")
    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


def run_optional_tools(path: Path) -> dict[str, Any]:
    tools: dict[str, Any] = {}
    c2patool = which("c2patool")
    if c2patool:
        try:
            r = subprocess.run(
                [c2patool, safe_arg(str(path))],
                capture_output=True,
                text=True,
                timeout=30,
                preexec_fn=subprocess_preexec_fn,
            )
            out = (r.stdout or "") + (r.stderr or "")
            low = out.lower()
            # Negative markers must veto every positive branch, so the
            # positive alternatives are parenthesised: c2patool reports a
            # missing manifest as "Error: No claim found", which contains
            # the substring "claim" and would otherwise read as a hit.
            no_manifest = "no claim" in low or "no jumbf" in low
            tools["c2patool"] = {
                "available": True,
                "returncode": r.returncode,
                "snippet": out[:2000],
                "has_manifest": (
                    "claim" in low or "c2pa" in low or "manifest" in low
                )
                and not no_manifest,
            }
        except Exception as e:
            tools["c2patool"] = {"available": True, "error": str(e)}
    else:
        tools["c2patool"] = {"available": False}

    exiftool = which("exiftool")
    if exiftool:
        try:
            r = subprocess.run(
                [exiftool, "-G1", "-a", "-s", safe_arg(str(path))],
                capture_output=True,
                text=True,
                timeout=30,
                preexec_fn=subprocess_preexec_fn,
            )
            out = r.stdout or ""
            interesting = [
                line
                for line in out.splitlines()
                if re.search(
                    r"c2pa|content.?credential|AIGC|digitalSource|XMP|EXIF|IPTC|jumb",
                    line,
                    re.I,
                )
            ]
            tools["exiftool"] = {
                "available": True,
                "interesting_lines": interesting[:50],
            }
        except Exception as e:
            tools["exiftool"] = {"available": True, "error": str(e)}
    else:
        tools["exiftool"] = {"available": False}
    return tools


def run_synthid_score(
    path: Path,
    upstream_dir: str | None = None,
) -> dict[str, Any] | None:
    """Run the optional reverse-SynthID scorer in a subprocess.

    Returns None when the scorer is not configured or unavailable (exit 3),
    so callers can keep the default "no SynthID score" behavior.
    """
    if upstream_dir is None:
        upstream_dir = os.environ.get("REVERSE_SYNTHID_DIR")
    if not upstream_dir:
        return None

    script = SCRIPTS_DIR / "score_synthid.py"
    cmd = [
        sys.executable,
        str(script),
        str(path),
        "--upstream-dir",
        str(upstream_dir),
        "--json",
    ]
    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=180,
            preexec_fn=subprocess_preexec_fn,
        )
    except Exception as e:
        return {"available": False, "error": str(e)}

    if r.returncode == 3:
        return None
    if r.returncode != 0:
        return {"available": False, "error": (r.stderr or "").strip()[:2000]}
    try:
        return json.loads(r.stdout or "{}")
    except json.JSONDecodeError as e:
        return {"available": False, "error": f"bad scorer JSON: {e}"}


def _ctrlregen_python(upstream: Path) -> str:
    """Prefer the checkout venv so torch/diffusers are importable."""
    if os.name == "nt":
        venv = upstream / ".venv" / "Scripts" / "python.exe"
    else:
        venv = upstream / ".venv" / "bin" / "python"
    if venv.is_file():
        return str(venv)
    return sys.executable


def run_ctrlregen_clean(
    path: Path,
    output: Path,
    *,
    upstream_dir: str | None = None,
    strength: float = 0.25,
    steps: int = 50,
    device: str | None = None,
    seed: int | None = None,
    timeout: int = 3600,
) -> dict[str, Any]:
    """Run the optional CtrlRegen removal in a subprocess.

    Returns ``{"available": False, "error": ...}`` when the backend is not
    configured, its dependencies are missing, or it fails at runtime; a
    successful run is ``{"available": True, ...}``.
    """
    if upstream_dir is None:
        upstream_dir = os.environ.get("NOAI_WATERMARK_DIR")
    if not upstream_dir:
        return {
            "available": False,
            "error": "CtrlRegen not configured (set NOAI_WATERMARK_DIR or pass --ctrlregen-dir)",
        }

    upstream = Path(upstream_dir).expanduser().resolve()
    if not upstream.is_dir():
        return {"available": False, "error": f"CtrlRegen dir not found: {upstream}"}

    script = SCRIPTS_DIR / "clean_ctrlregen.py"
    cmd = [
        _ctrlregen_python(upstream),
        str(script),
        str(path),
        "-o",
        str(output),
        "--upstream-dir",
        str(upstream),
        "--strength",
        str(strength),
        "--steps",
        str(steps),
        "--json",
    ]
    if device:
        cmd += ["--device", str(device)]
    if seed is not None:
        cmd += ["--seed", str(seed)]

    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            preexec_fn=ctrlregen_subprocess_preexec_fn,
        )
    except subprocess.TimeoutExpired:
        return {"available": False, "error": f"CtrlRegen timed out after {timeout}s"}
    except Exception as e:
        return {"available": False, "error": str(e)}

    if r.returncode != 0:
        return {"available": False, "error": (r.stderr or "").strip()[:2000]}
    try:
        payload = json.loads(r.stdout or "{}")
    except json.JSONDecodeError as e:
        return {"available": False, "error": f"bad CtrlRegen adapter JSON: {e}"}
    payload["available"] = True
    return payload


def inspect_image(
    path: Path,
    synthid_dir: str | None = None,
) -> ImageInspectReport:
    data = path.read_bytes()
    fmt = detect_format(data)
    if fmt == "png":
        has_c2pa, has_ai, findings = inspect_png(data)
    elif fmt == "jpeg":
        has_c2pa, has_ai, findings = inspect_jpeg(data)
    elif fmt == "webp":
        has_c2pa, has_ai, findings = inspect_webp(data)
    elif fmt == "tiff":
        has_c2pa, has_ai, findings = inspect_tiff(data)
    elif fmt == "gif":
        has_c2pa, has_ai, findings = inspect_gif(data)
    else:
        has_c2pa, has_ai, findings = False, False, ["unsupported format (MVP: PNG/JPEG/WebP/TIFF/GIF)"]

    notes: list[str] = []
    if fmt == "unknown":
        notes.append("format not fully inspected; PNG/JPEG/WebP/TIFF/GIF are supported")

    tools = run_optional_tools(path)
    # Elevate flags from tools
    ct = tools.get("c2patool") or {}
    if ct.get("has_manifest"):
        has_c2pa = True
        findings.append("c2patool reports a C2PA-related manifest")

    return ImageInspectReport(
        path=str(path),
        format=fmt,
        has_c2pa=has_c2pa,
        has_ai_metadata=has_ai,
        findings=findings,
        tools=tools,
        synthid=run_synthid_score(path, synthid_dir),
        notes=notes,
    )


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def strip_png(data: bytes, *, strip_all_text: bool = True) -> tuple[bytes, list[str]]:
    if not data.startswith(PNG_SIG):
        raise ValueError("not PNG")
    actions: list[str] = []
    out = bytearray(PNG_SIG)
    pos = 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        ctype = data[pos + 4 : pos + 8]
        chunk_start = pos + 8
        chunk_end = chunk_start + length
        if chunk_end + 4 > len(data):
            break
        payload = data[chunk_start:chunk_end]
        crc_bytes = data[chunk_end : chunk_end + 4]
        pos = chunk_end + 4
        name = ctype.decode("latin-1", errors="replace")

        drop = False
        if ctype in (b"eXIf", b"caBX") or ctype.startswith(b"c2"):
            drop = True
            actions.append(f"drop chunk {name}")
        elif ctype in (b"tEXt", b"zTXt", b"iTXt"):
            if strip_all_text or _contains_any(payload, AI_META_HINTS + C2PA_MARKERS):
                drop = True
                actions.append(f"drop chunk {name}")
        elif _contains_any(ctype + payload, C2PA_MARKERS) and ctype not in (
            b"IHDR",
            b"IDAT",
            b"IEND",
            b"PLTE",
            b"tRNS",
            b"gAMA",
            b"pHYs",
            b"sRGB",
            b"cHRM",
            b"iCCP",
        ):
            drop = True
            actions.append(f"drop chunk {name} (C2PA marker in payload)")

        if not drop:
            out.extend(struct.pack(">I", length) + ctype + payload + crc_bytes)
        if ctype == b"IEND":
            break
    if not actions:
        actions.append("no PNG metadata chunks removed (already clean or none matched)")
    return bytes(out), actions


def strip_jpeg(data: bytes, *, strip_all_app: bool = True) -> tuple[bytes, list[str]]:
    if not data.startswith(JPEG_SOI):
        raise ValueError("not JPEG")
    actions: list[str] = []
    out = bytearray(JPEG_SOI)
    i = 2
    n = len(data)
    while i < n:
        if data[i] != 0xFF:
            # unexpected; copy rest
            out.extend(data[i:])
            actions.append("copied remainder after non-marker byte")
            break
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1

        if marker == 0xD9:  # EOI
            out.extend(b"\xff\xd9")
            break
        if marker == 0xD8:  # nested SOI?
            continue
        if 0xD0 <= marker <= 0xD7:
            out.extend(bytes([0xFF, marker]))
            continue
        if marker == 0xDA:  # SOS — copy through end
            # need length of SOS header then entropy-coded data to EOI
            if i + 2 > n:
                break
            seglen = struct.unpack(">H", data[i : i + 2])[0]
            # Find EOI from here carefully: after SOS segment header, scan for FF D9
            # not preceded by stuffed FF 00 issues — simple approach: copy from FF DA to end
            sos_start = i - 2  # points at 0xFF before marker... actually marker already consumed
            # Reconstruct: FF DA + rest of file
            out.extend(b"\xff\xda")
            out.extend(data[i:])
            actions.append("preserved entropy-coded scan (SOS→EOF)")
            break

        if i + 2 > n:
            break
        seglen = struct.unpack(">H", data[i : i + 2])[0]
        if seglen < 2 or i + seglen > n:
            out.extend(data[i - 2 :])  # best effort
            actions.append("truncated segment; copied remainder")
            break
        payload = data[i + 2 : i + seglen]
        next_i = i + seglen

        # APP0 is JFIF — keep for compatibility unless full strip of all APP
        keep = False
        drop = False
        if 0xE0 <= marker <= 0xEF:  # APPn
            if marker == 0xEB:  # APP11 JUMBF/C2PA
                drop = True
                actions.append("drop APP11 (C2PA/JUMBF)")
            elif strip_all_app and marker != 0xE0:
                # keep APP0 (JFIF) by default
                drop = True
                actions.append(f"drop APP{marker - 0xE0}")
            elif _contains_any(payload, AI_META_HINTS + C2PA_MARKERS):
                drop = True
                actions.append(f"drop APP{marker - 0xE0} (AI/C2PA markers)")
            else:
                keep = True
        elif marker in (0xFE,):  # COM
            drop = True
            actions.append("drop COM comment")
        else:
            keep = True

        if keep and not drop:
            out.extend(bytes([0xFF, marker]))
            out.extend(data[i : i + seglen])
        i = next_i

    if not actions:
        actions.append("no JPEG APP segments removed")
    return bytes(out), actions


def strip_webp(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    """Drop EXIF/XMP chunks; clear the matching VP8X flag bits and fix RIFF size."""
    if data[:4] != WEBP_RIFF or data[8:12] != WEBP_MAGIC:
        raise ValueError("not WebP")
    actions: list[str] = []
    chunks: list[tuple[bytes, bytes]] = []
    dropped = {b"EXIF": False, b"XMP ": False}
    for fourcc, payload, truncated in _webp_chunks(data):
        name = fourcc.decode("latin-1", errors="replace")
        if truncated:
            actions.append(f"truncated chunk {name!r}; kept remainder verbatim")
            chunks.append((fourcc, payload))
            continue
        if fourcc in dropped:
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if strip_all_metadata or hits:
                dropped[fourcc] = True
                actions.append(f"drop {name} chunk" + (" (AI/C2PA markers)" if hits else ""))
                continue
        chunks.append((fourcc, payload))

    # VP8X advertises which optional chunks exist; stale EXIF/XMP bits make
    # some readers fail or hunt for missing chunks.
    if (dropped[b"EXIF"] or dropped[b"XMP "]) and chunks and chunks[0][0] == b"VP8X":
        flags = bytearray(chunks[0][1])
        if len(flags) >= 1:
            if dropped[b"EXIF"]:
                flags[0] &= 0xFF ^ 0x08
            if dropped[b"XMP "]:
                flags[0] &= 0xFF ^ 0x04
            chunks[0] = (chunks[0][0], bytes(flags))
            actions.append("cleared VP8X EXIF/XMP flag bits")

    body = bytearray(b"WEBP")
    for fourcc, payload in chunks:
        body += fourcc
        body += struct.pack("<I", len(payload))
        body += payload
        if len(payload) & 1:
            body += b"\x00"
    out = WEBP_RIFF + struct.pack("<I", len(body)) + bytes(body)
    if not actions:
        actions.append("no WebP metadata chunks removed")
    return out, actions


def strip_tiff(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    """Zero provenance tag values *in place* (same types/lengths/offsets).

    In-place zeroing avoids rewriting every strip offset in the file — the
    image data and structure stay byte-for-byte valid.
    """
    le = data[:4] == TIFF_LE
    if not le and data[:4] != TIFF_BE:
        raise ValueError("not TIFF")
    actions: list[str] = []
    out = bytearray(data)
    (ifd0,) = struct.unpack_from("<I" if le else ">I", data, 4)
    for tag, typ, cnt, val_off, entry in _tiff_walk_ifds(data, le, ifd0):
        if tag in _TIFF_TEXT_TAGS:
            hits = _contains_any(
                _tiff_value_bytes(data, le, typ, cnt, val_off, entry),
                AI_META_HINTS + C2PA_MARKERS,
            )
            if not (strip_all_metadata or hits):
                continue
            size = _TIFF_TYPE_SIZE.get(typ, 1) * cnt
            if size <= 4:
                out[entry + 8 : entry + 12] = b"\x00" * 4
            elif val_off + size <= len(out):
                out[val_off : val_off + size] = b"\x00" * size
            else:
                continue
            actions.append(f"zero tag {tag} ({_TIFF_TEXT_TAGS[tag]})")
        elif tag in (34665, 34853) and strip_all_metadata:
            # EXIF/GPS IFD pointer: zeroing the pointer detaches the whole
            # metadata tree without moving any bytes.
            out[entry + 8 : entry + 12] = b"\x00" * 4
            actions.append(f"zero tag {tag} ({'EXIF' if tag == 34665 else 'GPS'} IFD pointer)")
    if not actions:
        actions.append("no TIFF metadata tags zeroed")
    return bytes(out), actions


def strip_gif(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    """Drop comment extensions; keep animation/graphic-control/image blocks."""
    if data[:6] not in GIF_SIGS:
        raise ValueError("not GIF")
    actions: list[str] = []
    out = bytearray(data[:13])  # header + logical screen descriptor
    for block, kind, label in _gif_walk_blocks(data):
        if kind == "extension" and label == 0xFE:  # comment
            hits = _contains_any(block, AI_META_HINTS + C2PA_MARKERS)
            if strip_all_metadata or hits:
                actions.append("drop comment extension" + (" (AI/C2PA markers)" if hits else ""))
                continue
        if kind == "extension" and label == 0xFF:  # application extension
            hits = _contains_any(block, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                actions.append("drop application extension (AI/C2PA markers)")
                continue
        out += block
    if not actions:
        actions.append("no GIF comment/application extensions removed")
    return bytes(out), actions


def clean_image(
    path: Path,
    dest: Path,
    *,
    strip_all_metadata: bool = True,
    synthid_dir: str | None = None,
    remove_pixel: str | None = None,
    ctrlregen_dir: str | None = None,
    ctrlregen_strength: float = 0.25,
    ctrlregen_steps: int = 50,
    ctrlregen_device: str | None = None,
    ctrlregen_seed: int | None = None,
    ctrlregen_timeout: int = 3600,
) -> dict[str, Any]:
    synthid_before = run_synthid_score(path, synthid_dir)
    data = path.read_bytes()
    fmt = detect_format(data)
    if fmt == "png":
        cleaned, actions = strip_png(data, strip_all_text=strip_all_metadata)
    elif fmt == "jpeg":
        cleaned, actions = strip_jpeg(data, strip_all_app=strip_all_metadata)
    elif fmt == "webp":
        cleaned, actions = strip_webp(data, strip_all_metadata=strip_all_metadata)
    elif fmt == "tiff":
        cleaned, actions = strip_tiff(data, strip_all_metadata=strip_all_metadata)
    elif fmt == "gif":
        cleaned, actions = strip_gif(data, strip_all_metadata=strip_all_metadata)
    else:
        raise ValueError(f"unsupported format: {fmt}")

    # Optional exiftool pass for residual tags
    safe_write_bytes(dest, cleaned)
    exiftool = which("exiftool")
    if exiftool and strip_all_metadata:
        try:
            subprocess.run(
                [
                    exiftool,
                    "-all=",
                    "-overwrite_original",
                    safe_arg(str(dest)),
                ],
                capture_output=True,
                text=True,
                timeout=60,
                check=False,
                preexec_fn=subprocess_preexec_fn,
            )
            actions.append("exiftool -all= pass")
        except Exception as e:
            actions.append(f"exiftool failed: {e}")

    pixel_removal: dict[str, Any] | None = None
    if remove_pixel:
        if remove_pixel != "ctrlregen":
            raise ValueError(f"unknown pixel removal backend: {remove_pixel}")
        pixel_removal = run_ctrlregen_clean(
            dest,
            dest,
            upstream_dir=ctrlregen_dir,
            strength=ctrlregen_strength,
            steps=ctrlregen_steps,
            device=ctrlregen_device,
            seed=ctrlregen_seed,
            timeout=ctrlregen_timeout,
        )
        if pixel_removal.get("available"):
            actions.append(f"CtrlRegen pixel removal (strength {ctrlregen_strength})")
        else:
            actions.append(
                "CtrlRegen pixel removal skipped: "
                f"{pixel_removal.get('error', 'unknown error')}"
            )

    after = inspect_image(dest, synthid_dir=synthid_dir)
    return {
        "input": str(path),
        "output": str(dest),
        "format": fmt,
        "actions": actions,
        "bytes_in": len(data),
        "bytes_out": dest.stat().st_size,
        "still_has_c2pa": after.has_c2pa,
        "still_has_ai_metadata": after.has_ai_metadata,
        "post_findings": after.findings,
        "synthid_before": synthid_before,
        "synthid_after": after.synthid,
        "pixel_removal": pixel_removal,
    }
